# fly.toml app configuration file generated for citestproject on 2024-05-30T13:57:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'citestproject'
primary_region = 'cdg'

[env]
  PORT = "3000" # add this where PORT matches the internal_port below

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
